// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAvatarImg: typeof import('./../components/AppAvatarImg.vue')['default']
    AppDate: typeof import('./../components/AppDate.vue')['default']
    AppInfiniteScroll: typeof import('./../components/AppInfiniteScroll.vue')['default']
    AppNotifications: typeof import('./../components/AppNotifications.vue')['default']
    AppSpinner: typeof import('./../components/AppSpinner.vue')['default']
    CategoryList: typeof import('./../components/CategoryList.vue')['default']
    CategoryListItem: typeof import('./../components/CategoryListItem.vue')['default']
    ForumList: typeof import('./../components/ForumList.vue')['default']
    ModalDialog: typeof import('./../components/ModalDialog.vue')['default']
    PostEditor: typeof import('./../components/PostEditor.vue')['default']
    PostList: typeof import('./../components/PostList.vue')['default']
    ProfileCard: typeof import('./../components/ProfileCard.vue')['default']
    ProfileCardEditor: typeof import('./../components/ProfileCardEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavBar: typeof import('./../components/TheNavBar.vue')['default']
    ThreadEditor: typeof import('./../components/ThreadEditor.vue')['default']
    ThreadList: typeof import('./../components/ThreadList.vue')['default']
    ThreadListItem: typeof import('./../components/ThreadListItem.vue')['default']
  }
}
