// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAvatarFilePicker: typeof import('./../components/AppAvatarFilePicker.vue')['default']
    AppAvatarImg: typeof import('./../components/AppAvatarImg.vue')['default']
    AppAvatarRandomPicker: typeof import('./../components/AppAvatarRandomPicker.vue')['default']
    AppDate: typeof import('./../components/AppDate.vue')['default']
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppFormField: typeof import('./../components/AppFormField.vue')['default']
    AppInfiniteScroll: typeof import('./../components/AppInfiniteScroll.vue')['default']
    AppNavConfirmationModal: typeof import('./../components/AppNavConfirmationModal.vue')['default']
    AppNotifications: typeof import('./../components/AppNotifications.vue')['default']
    AppSpinner: typeof import('./../components/AppSpinner.vue')['default']
    CategoryList: typeof import('./../components/CategoryList.vue')['default']
    CategoryListItem: typeof import('./../components/CategoryListItem.vue')['default']
    ForumList: typeof import('./../components/ForumList.vue')['default']
    PaginationV: typeof import('@hennge/vue3-pagination')['default']
    PostEditor: typeof import('./../components/PostEditor.vue')['default']
    PostList: typeof import('./../components/PostList.vue')['default']
    PostListItem: typeof import('./../components/PostListItem.vue')['default']
    ProfileCard: typeof import('./../components/ProfileCard.vue')['default']
    ProfileCardEditor: typeof import('./../components/ProfileCardEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavBar: typeof import('./../components/TheNavBar.vue')['default']
    ThreadEditor: typeof import('./../components/ThreadEditor.vue')['default']
    ThreadList: typeof import('./../components/ThreadList.vue')['default']
    ThreadListItem: typeof import('./../components/ThreadListItem.vue')['default']
    VeeErrorMessage: typeof import('vee-validate')['ErrorMessage']
    VeeField: typeof import('vee-validate')['Field']
    VeeForm: typeof import('vee-validate')['Form']
  }
}
