import { reactive } from "vue";
import { remove } from "../utils/array-helpers";
import { guidAsBase64 } from "../utils/misc";

export interface Notification {
  id: string;
  message: string;
}

const notifications = reactive<Array<Notification>>([]);

/**
 * @returns {string} `id` of new notification, either autogenerated or consumer provided.
 */
function addNotification(
  message: string,
  id: string | number = guidAsBase64()
): string {
  id = String(id);
  notifications.push({ id, message });

  return id;
}

function removeNotification(id: string) {
  remove(notifications, ({ id: nId }) => nId === id);
}

export default function useNotifications() {
  return {
    addNotification,
    removeNotification,
    notifications,
  };
}
