import { reactive } from "vue";
import { guidAsBase64 } from "../utils/misc";

const notifications = reactive(new Map<string, string>());

/**
 * @returns {string} `id` of new notification, either autogenerated or consumer provided.
 */
function addNotification(
  message: string,
  timeoutMs?: number,
  id: string | number = guidAsBase64()
): string {
  id = String(id);
  notifications.set(id, message);

  timeoutMs && setTimeout(() => removeNotification(id), timeoutMs);

  return id;
}

function removeNotification(id: string | number) {
  notifications.delete(String(id));
}

export default function useNotifications() {
  return {
    addNotification,
    removeNotification,
    notifications,
  };
}
